version: '3.8'

services:
  bulk-email-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bulk-email-app
    env_file:
      - .env
    volumes:
      - ./emails.db:/app/emails.db
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - bulk-email-network
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx Reverse Proxy
  bulk-email-nginx:
    image: nginx:alpine
    container_name: bulk-email-nginx
    ports:
      - "8080:80"
    volumes:
      # Configuration Nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Logs Nginx
      - ./nginx/logs:/var/log/nginx
      # SSL (décommenter si vous avez des certificats)
      # - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - bulk-email-app
    restart: unless-stopped
    networks:
      - bulk-email-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bulk-email-network:
    driver: bridge
